language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot readme.md --allow-dupe --white-list https://fosdem.org/ https://moaifiddle.com
notifications:
  email: false
